---
- hosts: default
  tasks:
    - name: install dependencies
      become: yes
      apt:
        name:
          - qemu-utils
          - qemu-system-x86
          - dosfstools
          - clang
          - build-essential
          - lld
          - uuid-dev
          - llvm
          - nasm
    # install EDK2
    - name: clone EDK2
      git:
        repo: "https://github.com/tianocore/edk2.git"
        dest: "{{ ansible_env.HOME }}/edk2"
        version: "38c8be123aced4cc8ad5c7e0da9121a181b94251"
    - name: build EDK2
      make:
        chdir: "{{ ansible_env.HOME }}/edk2/BaseTools/Source/C"
    # install standard libraries
    - name: create directory if not exists
      file:
        path: "{{ ansible_env.HOME }}/library"
        state: directory
        mode: 0775
    - name: install standard libraries
      unarchive:
        src: "https://github.com/uchan-nos/mikanos-build/releases/download/v1.0/x86_64-elf.tar.gz"
        dest: "{{ ansible_env.HOME }}/library"
        remote_src: yes
