FROM ubuntu:20.04

WORKDIR /app

RUN apt update
# 別でインストールしないとlocationの設定で入力待ちになる
RUN apt install -y tzdata
RUN apt install -y \
  qemu-utils \
  qemu-system \
  dosfstools \
  clang \
  build-essential \
  lld
