[build]
target = "x86_64-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = [
  "-C", "no-redzone=yes",
  "-C", "relocation-model=static",
  "-C", "link-arg=--entry=KernelMain",
  "-C", "link-arg=--image-base=0x100000",
]
