[build]
target = "x86_64-unknown-linux-gnu"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[target.x86_64-unknown-linux-gnu]
linker = "rust-lld"

rustflags = [
  "-C", "no-redzone=yes",
  "-C", "relocation-model=static",
  "-C", "link-arg=--entry=KernelMain",
  "-C", "link-arg=--image-base=0x100000",
]
