#!/bin/bash
DIR=$(cd $(dirname $0); pwd)
PWD=$(pwd)
BUILD_PATH=tmp
EFI_FILE_PATH=$1

mkdir -p $BUILD_PATH

# build
qemu-img create -f raw $BUILD_PATH/disk.img 200M
mkfs.fat -n 'os' -s 2 -f 2 -R 32 -F 32 $BUILD_PATH/disk.img
mkdir -p $BUILD_PATH/mnt
sudo mount -o loop $BUILD_PATH/disk.img $BUILD_PATH/mnt
sudo mkdir -p $BUILD_PATH/mnt/EFI/BOOT
sudo cp $EFI_FILE_PATH $BUILD_PATH/mnt/EFI/BOOT/BOOTX64.efi
sudo umount $BUILD_PATH/mnt

# run
qemu-system-x86_64 \
  -drive if=pflash,format=raw,file=$DIR/OVMF_CODE.fd \
  -drive if=pflash,format=raw,file=$DIR/OVMF_VARS.fd \
  -drive if=ide,format=raw,file=$BUILD_PATH/disk.img

# clean up
rm -rf $BUILD_PATH
